#!/usr/bin/env python3.6

import subprocess
import argparse

def main(core):
    result = subprocess.run('ps -eo pid,psr,command,euser', shell=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    output = result.stdout.decode()
    rows = output.splitlines()
    header = rows[0]
    print(header)
    for row in rows[1:]:
        cpu = int(row.split()[1])
        if cpu == core:
            print(row)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--core', required=True, type=int, help='cpu to be used(0 based)')
    args = parser.parse_args()

    main(args.core)
